# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWindow(object):
    def setupUi(self, SelectWindow):
        SelectWindow.setObjectName("SelectWindow")
        SelectWindow.resize(1017, 836)
        self.verticalLayoutWidget = QtWidgets.QWidget(SelectWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 702, 760))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Name.setAutoFillBackground(False)
        self.label_Name.setObjectName("label_Name")
        self.verticalLayout.addWidget(self.label_Name)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_Image = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Image.setMinimumSize(QtCore.QSize(700, 700))
        self.label_Image.setMouseTracking(False)
        self.label_Image.setObjectName("label_Image")
        self.verticalLayout.addWidget(self.label_Image)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label_Number = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Number.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Number.setObjectName("label_Number")
        self.verticalLayout.addWidget(self.label_Number)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(SelectWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(780, 40, 181, 231))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_Change = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_Change.setObjectName("pushButton_Change")
        self.verticalLayout_3.addWidget(self.pushButton_Change)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pushButton_Previous = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_Previous.setObjectName("pushButton_Previous")
        self.verticalLayout_3.addWidget(self.pushButton_Previous)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.pushButton_Next = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.verticalLayout_3.addWidget(self.pushButton_Next)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_skip = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_skip.setObjectName("lineEdit_skip")
        self.horizontalLayout.addWidget(self.lineEdit_skip)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton_Skip = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_Skip.setObjectName("pushButton_Skip")
        self.horizontalLayout.addWidget(self.pushButton_Skip)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.pushButton_Restore = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_Restore.setObjectName("pushButton_Restore")
        self.verticalLayout_3.addWidget(self.pushButton_Restore)

        self.retranslateUi(SelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectWindow)

    def retranslateUi(self, SelectWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectWindow.setWindowTitle(_translate("SelectWindow", "Select Images"))
        self.label_Name.setText(_translate("SelectWindow", "path"))
        self.label_Image.setText(_translate("SelectWindow", "Image"))
        self.label_Number.setText(_translate("SelectWindow", "1/100"))
        self.pushButton_Change.setText(_translate("SelectWindow", "View Front"))
        self.pushButton_Previous.setText(_translate("SelectWindow", "Previous"))
        self.pushButton_Next.setText(_translate("SelectWindow", "Next"))
        self.pushButton_Skip.setText(_translate("SelectWindow", "Skip"))
        self.pushButton_Restore.setText(_translate("SelectWindow", "Restore"))
